language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
services:
  - postgresql
  - mysql
cache: cargo
rust:
  - stable
  - nightly
env:
  - DATABASE_URL=postgres://casbin_rs:casbin_rs@localhost:5432/casbin; POOL_SIZE=8;
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add rustfmt
  - psql -c "CREATE DATABASE casbin;" -U postgres
  - psql -c "CREATE USER casbin_rs WITH PASSWORD 'casbin_rs';" -U postgres
  - psql postgres://casbin_rs:casbin_rs@127.0.0.1:5432/casbin -c "CREATE TABLE IF NOT EXISTS casbin_rules (
    id SERIAL PRIMARY KEY,
    ptype VARCHAR NOT NULL,
    v0 VARCHAR NOT NULL,
    v1 VARCHAR NOT NULL,
    v2 VARCHAR NOT NULL,
    v3 VARCHAR NOT NULL,
    v4 VARCHAR NOT NULL,
    v5 VARCHAR NOT NULL,
    CONSTRAINT unique_key_sqlx_adapter UNIQUE(ptype, v0, v1, v2, v3, v4, v5)
    );"
  - mysql -u root -e "CREATE DATABASE casbin;"
  - mysql -u root -e "CREATE USER 'casbin_rs'@'localhost' IDENTIFIED BY 'casbin_rs'; GRANT ALL ON casbin.* TO 'casbin_rs'@'localhost';"
  - mysql -u casbin_rs -p'casbin_rs' -e "USE casbin; CREATE TABLE IF NOT EXISTS casbin_rules (
    id INT NOT NULL AUTO_INCREMENT,
    ptype VARCHAR(12) NOT NULL,
    v0 VARCHAR(128) NOT NULL,
    v1 VARCHAR(128) NOT NULL,
    v2 VARCHAR(128) NOT NULL,
    v3 VARCHAR(128) NOT NULL,
    v4 VARCHAR(128) NOT NULL,
    v5 VARCHAR(128) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT unique_key_sqlx_adapter UNIQUE(ptype, v0, v1, v2, v3, v4, v5)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;"

script:
  - cargo clean
  - cargo build --no-default-features --features postgres,runtime-async-std
  - cargo test --no-default-features --features postgres,runtime-async-std
  - export DATABASE_URL=mysql://casbin_rs:casbin_rs@localhost:3306/casbin
  - cargo build --no-default-features --features mysql,runtime-async-std
  - cargo test --no-default-features --features mysql,runtime-async-std
  - cargo fmt --all -- --check

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # upload report to codecov
    export DATABASE_URL=postgres://casbin_rs:casbin_rs@localhost:5432/casbin
    cargo install cargo-tarpaulin
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi