language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
services:
  - postgresql
cache: cargo
rust:
  - stable
  - nightly
env:
  - DATABASE_URL=postgres://casbin_rs:casbin_rs@localhost:5432/casbin; POOL_SIZE=8;
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add rustfmt
  - psql -c "CREATE DATABASE casbin;" -U postgres
  - psql -c "CREATE USER casbin_rs WITH PASSWORD 'casbin_rs';" -U postgres
  - psql -c "CREATE TABLE IF NOT EXISTS casbin_rules (
    id SERIAL PRIMARY KEY,
    ptype VARCHAR NOT NULL,
    v0 VARCHAR NOT NULL,
    v1 VARCHAR NOT NULL,
    v2 VARCHAR NOT NULL,
    v3 VARCHAR NOT NULL,
    v4 VARCHAR NOT NULL,
    v5 VARCHAR NOT NULL,
    CONSTRAINT unique_key UNIQUE(ptype, v0, v1, v2, v3, v4, v5)
    );" -U casbin_rs

script:
  - cargo clean
  - cargo build
  - cargo test
  - cargo fmt --all -- --check